### ISSUE TITLE
Touch pin connection

### ISSUE THREAD

**Issue by poky** [Smashcat/circular-display-prototyping-board#1]
Hi, thanks for the awesome project!

Since the touch is using the I2C interface, do I use the default 21 & 22 pins for SCL & SDA? (I'm using ESP32)

**Comment by Smashcat** [comment]
Thanks! Yep, 21 and 22 for i2c. You should also put pullups on those pins to ensure they work properly (usually 4k7 will work fine)

**Comment by Smashcat** [comment]
No further actions.
